@startuml
component core {
	package mymovies.core
	package mymovies.json
}

component restserver {
	package mymovies.restserver
}

component integrationtests{
	package mymovies.webapp
}

component fxui {
	package mymovies.ui
}

component javafx {
	component fxml {
	}
}

component jackson {
}

component jersey {
}

component springboot{
}

component jetty{
}

mymovies.json ..> jackson

mymovies.ui ..> mymovies.core
mymovies.ui ..> mymovies.json

fxui ..> javafx
fxui ..> fxml

integrationtests ..> jetty
integrationtests ..> jersey
integrationtests ..> springboot

mymovies.webapp ..> mymovies.core
mymovies.webapp ..> mymovies.json

mymovies.restserver ..> mymovies.core

restserver ..> jackson
restserver ..> springboot
@enduml
