@startuml
component core {
	package mymovies.core
	package mymovies.json
}

component restserver {
	package mymovies.restserver
}

component fxui {
	package mymovies.ui
}

component javafx {
	component fxml {
	}
}

component jackson {
}

component springboot{
}

mymovies.json ..> jackson

mymovies.ui ..> mymovies.core
mymovies.ui ..> mymovies.json

fxui ..> javafx
fxui ..> fxml


mymovies.restserver ..> mymovies.core

restserver ..> jackson
restserver ..> springboot
@enduml