@startuml
actor Person
Person-> "~#submitButton: \nButton" as submitButton: click

submitButton -> MyMoveisController : handleSubmit()

MyMoveisController -> "~#name: \nTextField" as name: getText()
MyMoveisController -> "~#rating: \ncombobox" as rating: getValue()
MyMoveisController -> "~#genre: \ncomboBox" as genre: getValue()

MyMoveisController -> User: addMovie(Film)

MyMoveisController -> RemoteUserAccess: updateUser()
MyMoveisController -> MyMoveisController: submitted()

RemoteUserAccess -> ObjectMapper: writeValueAsString
ObjectMapper --> RemoteUserAccess: a JSON string


RemoteUserAccess -> AllUsersController: HTTP PUT "/" \n-> updateUser

AllUsersController -> AllUsersService: getAllUsers()

AllUsersController -> AllUsers: getUser(username)
AllUsersController -> RemoteUserAccess: updateUser(user)
AllUsersController --> RemoteUserAccess: ResponseEntity<>(String, HttpStatus)

RemoteUserAccess -> AllUsers: updateUser(user)
@enduml